import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <AuthProvider>
          <div className="container max-w-6xl mx-auto px-8 sm:px-12 md:px-16">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
