import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-serif">
        <AuthProvider>
          <div className="container max-w-6xl mx-auto px-4 sm:px-12">
            {children}
          </div>
        </AuthProvider>
        <Toaster/>
      </body>
    </html>
  );
}
